### PR TITLE
Support plugin archives

### PR DESCRIPTION
**Pull request by aalmiray**
Fix for #39.

Supported plugin archives are: `.jar`, `.zip`, `.tar`, `.tar.gz`.

### CODE REVIEW

**Review by gunnarmorling — COMMENTED** [review]
Nice! The one thing I'm wondering about: can we add an automated test? IIRC, the Vert.x example did fullfill this function. Perhaps we should actually bring it back here?

**Comment by aalmiray** [comment]
Indeed. We have a plugin test but it does not load/unload like the vert.x example did. I can add that to the existing test.

**Comment by aalmiray** [comment]
Tried a few things with the current `PluginExampleTest` class to deal with dynamically loaded plugins, does not look good. The test must use a pair of threads to execute the program _and_ send inputs, it just complicates matters.
Bringing back the vert.x example seems like a better approach to test dynamic plugins.

**Comment by gunnarmorling** [comment]
> Bringing back the vert.x example seems like a better approach to test dynamic plugins.

Are you planning to do this as part of this PR then? Or rather separately?

**Comment by aalmiray** [comment]
I've got the test in place but it's failing with CNFEs when assembling the layers for the first time. I'll do a manual test on the external vert.x example (as I have done for the modular-tiles). If it works then I'll split the test into a different PR as a successful manual test tells me the production code works but the test infrastructure is not properly configured.

**Comment by aalmiray** [comment]
I've manually checked the external vert.x example with the changes stemming form this PR and it works flawlessly. @gunnarmorling I think we're good to go with this PR. Once merged, I'll send another with the vert.x example as testcase.

**Review by gunnarmorling — APPROVED** [review]
Very nice, thx a lot!

**Pull request merged**
