### PR TITLE
Remove dependency on Java 14

### PR DESCRIPTION
**Pull request by brunoborges**
Fixes issue #18

### CODE REVIEW

**Comment by aalmiray** [comment]
@brunoborges looks like you have mixed formatting settings in your editor, some of your proposed changes are whitespace chars and indentation.

**Comment by gunnarmorling** [comment]
Yeah, would be good to revert all the formatting changes, thanks!

On the actual issue, it has been a while, but I think I used the embedded HTML text block due to some classloading issue with Vert.x. It wouldn't allow me to pass my module layer's classloader for loading a resource.

**Comment by gunnarmorling** [comment]
So maybe Java 14 for building and testing Layrry, but emitting JDK 11 byte code format for wider compatibility?

**Comment by gunnarmorling** [comment]
Hey @brunoborges, do you still plan to rework this one along the lines discussed above?

**Comment by brunoborges** [comment]
Urgh yes. I do. It's moving week for me, this why I haven't progressed on this. 

I should be able to work on it next week

**Comment by aalmiray** [comment]
FYI build now requires JDK15.

**Comment by brunoborges** [comment]
@aalmiray so building requires 15, but not running, right?

**Comment by gunnarmorling** [comment]
Yes, right, it should still be able to run with 11. The requirement for
newer than that for building Layrry is due to the Vert.x example. Perhaps
we move that over to the layrry-examples repo now?

>

**Comment by aalmiray** [comment]
Agreed, we can move the Vert.x example to layrry-examples, however we probably need a few extra testcases as I believe this particular example was sensitive to recent refactorings as was crucial to finding out bugs.

**Pull request closed without merging**
